# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build and test with Maven
      run: mvn clean install
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag waracle-cake-manager:$(date +%s)
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: chipples/waracle-cake-manager:latest
    - name: Get Timestamp
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Run String Replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
    - name: Generate Deployment Package
      run: zip deploy.zip Dockerrun.aws.json
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: waracle-cake-manager
        environment_name: Waraclecakemanager-env
        version_label: "waracle-cake-manager-${{ steps.format-time.outputs.replaced }}"
        region: us-west-2
        deployment_package: deploy.zip
